### ISSUE TITLE
Data files incorrectly formatted

### ISSUE THREAD

**Issue by drStacky** [microsoft/KenyaNigeriaBuildingFootprints#1]
Each line of the `geojsonl` files contains an entire `FeatureCollection` instead of just the `Feature`. This prevents packages like GDAL from reading the files. See [here](https://stevage.github.io/ndgeojson/) for reference.
Current line:
```
{"type": "FeatureCollection", "features": [{"geometry": {"type": "Polygon", "coordinates": [[[3.517953247586725, 13.91314207544103], [3.517994974782424, 13.91314891003471], [3.517985733243849, 13.9132020701834], [3.51794400604815, 13.9131952355913], [3.517953247586725, 13.91314207544103]]]}, "properties": {}, "type": "Feature"}]}
```
Correct line:
```
{"geometry": {"type": "Polygon", "coordinates": [[[3.517953247586725, 13.91314207544103], [3.517994974782424, 13.91314891003471], [3.517985733243849, 13.9132020701834], [3.51794400604815, 13.9131952355913], [3.517953247586725, 13.91314207544103]]]}, "properties": {}, "type": "Feature"}
```

**Comment by denironyx** [comment]
I noticed a similar mistake @drStacky.

**Comment by jeafreezy** [comment]
+1 @drStacky @denironyx

**Comment by drnextgis** [comment]
@drStacky can you try to open it with GeoJSONSeq GDAL driver?

**Comment by drnextgis** [comment]
It seems GDAL only supports sequences of GeoJSON features (not feature collections). But the original dataset (data.njson) can be easily transformed to a proper one (output.njson):
```python
import json
with open("data.njson", "rt") as src:
    with open("output.njson", "w") as dst:
        for row in src:
            fc = json.loads(row)
            for f in fc["features"]:
                json.dump(f, dst)
                dst.write("\n")
```

**Comment by jeafreezy** [comment]
I have a similar script that is currently taking forever to run.

Please how long does this script take you? @drnextgis

**Comment by drStacky** [comment]
Python will take forever to parse a file that size. I'm sure there's a more elegant way to do this, but I used a BASH command from the terminal that completed in a relatively short time.
```
cat incorrect.geojsonl | cut -c 44- | sed 's/]}$//' > correct.geojsonl
```
Now can someone at Microsoft do this to all the files and upload them again, please?

**Comment by simgislab** [comment]
@drnextgis  script is pretty good, kenya file takes around 30 min to run on a regular server, nigeria is longer, but overnight would be ok

it's a one time conversion after all

**Comment by jeafreezy** [comment]
Yeah, it's a nice script. Nigeria took me about 1hr on 16gig ram windows 11 1TD SSD. Thanks @drStacky

**Comment by andwoi** [comment]
Thanks for notifying us. Both Kenya and Nigeria were updated today and can be found in the same locations.
